from policies.full_pilot import FullPilotPolicy
from policies.laggy_pilot import LaggyPilotPolicy
from policies.noisy_pilot import NoisyPilotPolicy
from policies.noop_pilot import NoopPilotPolicy
from policies.sensor_pilot import SensorPilotPolicy
from policies.co_pilot import CoPilotPolicy